### ISSUE TITLE
Давно такого не видел

### ISSUE THREAD

**Issue by jefry** [Nesmark/AskaAssistentSystem#1]
https://github.com/Nesmark/AskaAssistentSystem/blob/dacdf50d3cd19f77f29239bfc026e5aa1645b9f7/aska_script/polival_kystu.js#L17

попробуй сделать масивами
етот код плохо для репутации

пс ответь на письмо

**Comment by HydraFire** [comment]
Вот так лучше?

https://github.com/Nesmark/AskaAssistentSystem/blob/f26e4859f840c7a2f40e94a78baf21017131bd71/aska_script/polival_kystu.js#L8





12 сентября 2017 г., 19:04 пользователь jefry <notifications@github.com>
написал:

**Comment by HydraFire** [comment]
Не проверял вчера почьту, не видел что ты звал кофе пить. Если что сегодня
пиши.

13 сентября 2017 г., 15:10 пользователь Ярослав Коваль <
hydrafire.plus@gmail.com> написал:
